# Day 3 Assignment Solutions


In [83]:
'''Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.'''
                                                                                                      # Answer for Question 1
import numpy as np
a = np.arange(2,50,3, dtype=None)
print(a)                                              

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [22]:
"""Questions 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it. """
                                                                                                       # Answer for question 2
lst1 = []                                                                                              
lst2 = [] 

a = int(input("Enter number of elements for list 1 : "))  
for i in range(0, a): 
    value1 = int(input())                                  
    lst1.append(value1)                               # list 1 creation
    
b =  int(input("Enter number of elements list 2 : ")) 
for i in range(0, b): 
    value2 = int(input()) 
    lst2.append(value2)                               # list 2 creation
    
print("List 1",lst1)                 
print("List 2",lst2) 

import numpy as np

arr1 = np.array(lst1)                               # array 1 creation
arr2 = np.array(lst2)                               # array 2 creation
print("Array 1", arr1,'\n',"Array 2", arr2)   

arr3 = np.concatenate((arr1, arr2))                 # concatination of arrays
print("Concatenated Array", arr3)
print("Sorted array",np.sort(arr3))                 # sorting the array values

Enter number of elements for list 1 : 5
89
75
44
66
12
Enter number of elements list 2 : 5
12
45
78
36
54
List 1 [89, 75, 44, 66, 12]
List 2 [12, 45, 78, 36, 54]
Array 1 [89 75 44 66 12] 
 Array 2 [12 45 78 36 54]
Concatenated Array [89 75 44 66 12 12 45 78 36 54]
Sorted array [12 12 36 44 45 54 66 75 78 89]


In [32]:
"""Question 3:

Write a code snippet to find the dimensions of a ndarray and its size."""

import numpy as np                                                                                    # Answer for question 3

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5],
                 [9,7,8]] )

print("No. of dimensions: ", arr.ndim)                        # Dimension of the array 
print("Size of array: ", arr.size)                            # Size of the array

No. of dimensions:  2
Size of array:  9


In [63]:
"""Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims"""
                                                                                                      # Answer for Question 4
# Solution
#-------------------------------------------------------------------------------------------------------------------------------
#  Converting 1D array to 2D array is done by using "np.newaixs" - which is used to increase the dimension
#  of the existing array by one more dimension, when used once. "1D array will become 2D array"
#  We can also expand our array by using "numpy.expand_dims(a, axis)" - which is Used to expand the shape of an array.
#-------------------------------------------------------------------------------------------------------------------------------
import numpy as np

arr = np.array([ 1, 2, 3, 4, 5, 6])
print(arr)
print("Dimension is : ", arr.ndim)
print("Dimensions are converted using np.newaxis")
arr1 = arr[:, np.newaxis]                               # Converting 1D array to 2D array using "np.newaxis"    # column vector
arr2 = arr[np.newaxis, :]                                                                                       # row vector
#print("Column vector : ",arr1)
#print("Row Vector : ",arr2)
print("Dimension is (Column vector) : ", arr1.ndim)
print("Dimension is (Row vector) : ", arr2.ndim)


# np.expand_dims - is similar np.newaxis, which can also be used to insert one dimension to an arrary

arr3 = np.array([9, 8, 7, 6, 5])
print(arr3)
print("Dimensions is : ", arr3.ndim)
arr4 = np.expand_dims(arr3, 1) 
arr5 = np.expand_dims(arr3, 0)  
print("Dimensions converted using np.expand_dims")
print("Dimension is (Column vector) : " , arr4.ndim)
print("Dimension is (Row Vector) : ", arr5.ndim)

[1 2 3 4 5 6]
Dimension is :  1
Dimensions are converted using np.newaxis
Dimension is (Column vector) :  2
Dimension is (Row vector) :  2
[9 8 7 6 5]
Dimensions is :  1
Dimensions converted using np.expand_dims
Dimension is (Column vector) :  2
Dimension is (Row Vector) :  2


In [82]:
"""Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()"""
                                                                                                      # Answer for Question 5
import numpy as np

u = np.square([1,2,3,4,5,6,7,8,9])                                  # Squaring the array 1
v = np.square([9,8,7,6,5,4,3,2,1])                                  # Squaring the array 2                  
w = np.vstack((u,v))                                                # Vertically Stacked 
print("Vertical stack",w)
x = np.hstack((u,v))                                                # Horizontally stacked
print("Horizontal Stack",x)                                                            

Vertical stack [[ 1  4  9 16 25 36 49 64 81]
 [81 64 49 36 25 16  9  4  1]]
Horizontal Stack [ 1  4  9 16 25 36 49 64 81 81 64 49 36 25 16  9  4  1]


In [78]:
"""Questions 6:

How to get unique items and counts of unique items?"""
                                                                                                        # Answer for Question 6
import numpy as np                                                       

z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 5, 6, 0])
#print(np.unique(z))                                                  # printing unique items
print(np.unique(z, return_counts=True))                               # printing count of unique items

x= np.array(["a","b", "c", "d", "a", "z","c"])
print(np.unique(x, return_counts=True))                     


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 2, 2, 2, 1, 1], dtype=int64))
(array(['a', 'b', 'c', 'd', 'z'], dtype='<U1'), array([2, 1, 2, 1, 1], dtype=int64))
